### ISSUE TITLE
Difference between 0.4.0 and 0.6.0 may be a bug?

### ISSUE THREAD

**Issue by xywang68** [maugenst/tabletojson#14]
Hi, thanks for providing this convenient tool.
We noticed a table parse difference after we upgrade from 0.4.0 to 0.6.0.
In 0.4.0 tabletojson parsed our table into:
![image](https://user-images.githubusercontent.com/9934557/27497370-12ad9a78-580f-11e7-8122-ce3d75bb3258.png)
While in 0.6.0 it parsed into
![image](https://user-images.githubusercontent.com/9934557/27497392-36769f40-580f-11e7-9c74-464b54ff92c0.png)
The table looks like this:
![image](https://user-images.githubusercontent.com/9934557/27497582-3ca57174-5810-11e7-8f61-ab3ed3c0d0a5.png)
As you can see, column 4 and 5 (start from 0, the 2 little icon images) has no name.
In 0.4.0 columns without names are represented in column numbers, and sorted alphabetically with the rest of the columns.
In 0.6.0 this seems to be different. the "_2" column seems to be a bug.

**Comment by iaincollins** [comment]
Oh dear I'm sorry about that. I don't think tables with no names had been thought about in recent changes. I'll see if we can finally add some tests and get this sorted.

Thanks for raising the issue!

**Comment by xywang68** [comment]
Thank you!

**Comment by maugenst** [comment]
Hopefully fixed this in version 0.9.2. I implemented it in the way that if an column has no header it's field's number will be taken as the property name in the resulting object. Hope this is the way you intended it to be. Please get back to me if this does not fit your needs and I will reopen this issue for you.

Thanks and best regards, Marius
