### ISSUE TITLE
Problem with duplicate column headings

### ISSUE THREAD

**Issue by neergaard79** [maugenst/tabletojson#15]
There seems to be an issue with the duplicate column detection when two (or more) tables are converted. This worked differently in v. 0.4.0 at least.

**0.6.0 Output:**
`[
    [{
        "Column1": "C1",
        "Column2": "C2"
    }],
    [{
        "Column1_2": "C1",
        "Column2_2": "C2"
    }]
]`

**0.4.0 Output (correct):**
`[
    [{
        "Column1": "C1",
        "Column2": "C2"
    }],
    [{
        "Column1": "C1",
        "Column2": "C2"
    }]
]`

**Comment by iaincollins** [comment]
Thanks so much for submitting and with details, it seemed like there was something up.

This is super helpful.

I'll spend some time at the weekend to create tests and resolve these.

**Comment by iaincollins** [comment]
I still have not gotten around to this, but see also #26 and #18

**Comment by maugenst** [comment]
This issue will be fixed with version 0.9.2. Thanks for raising and describing it. I'm going to push the fix in the next minutes.
