### ISSUE TITLE
Issue with japanese page

### ISSUE THREAD

**Issue by Nordes** [maugenst/tabletojson#19]
Somehow, if the page is in Japanese the character are HTML encoded if we want to keep the HTML and then it is converted properly if we ask only the text.

```html
<html><head><meta http-equiv="Content-Type" content="text/html; charset=x-sjis"></head>
...分から....
</html>
```

If the option is to convert are 
```javascript
// Code
tabletojson.convert(rawHtmlData, { useFirstRowForHeadings: true, stripHtml:false });
// Code
```

The result give the data with the encoded characters. `[&#x5099;&#x8003;]` instead of the real Japanese characters.

To fix the issue for now I did the following:

Ref.: https://stackoverflow.com/questions/16400641/can-hexadecimal-html-be-systematically-converted-to-unicode-via-javascript
```javascript
function decodeCharRefs(string) {
  return string
      .replace(/&#(\d+);/g, function(match, num) {
          return String.fromCharCode(num);
      })
      .replace(/&#x([A-Za-z0-9]+);/g, function(match, num) {
          return String.fromCharCode(parseInt(num, 16));
      });
}

decodeCharRefs(myResult)
```

**Comment by maugenst** [comment]
I've lately added a test (0.9.4) to check the conversion of web pages containing japanese signs. It worked well. Please check on how you read your rawData and use utf-8.
Please also have a look into the examples and the tests and reopen this issue if your problem still exists. 

Best regards, Marius
