### ISSUE TITLE
Problems with encoding special characters in the table

### ISSUE THREAD

**Issue by franzz2000** [maugenst/tabletojson#31]
When converting url I get problems with the converted JSON. I download a Spanish page with accents. The text will show letters with question marks instead of the correct letter.

An example is the next url which is utf8 encoded:

http://competiciones.feb.es/estadisticas/Resultados.aspx?g=1&t=2018

Franz Jimeno

**Comment by franzz2000** [comment]
Just solved the problem. Had to add {request: {encoding:'binary'}} as an argument in convertUrl.

**Comment by maugenst** [comment]
Thanks for the response Franz.

**Comment by mapecode** [comment]
My solution with `request-promise` package:

```javascript
const result = await request({ uri: url, encoding: 'latin1' })
const converted = tabletojson.convert(result)
```
