### ISSUE TITLE
Adding support for Complex Rowspans

### ISSUE THREAD

**Issue by maugenst** [maugenst/tabletojson#44]
Like described here: 
[Complex Rowspans](https://github.com/maugenst/tabletojson/blob/complexRowspans/README.md#tables-with-complex-rowspan)

It would be nice to support also Complex rowspans that lead to correct objects.

**Comment by maugenst** [comment]
Already added a failing test on this issue.
[test Complex Rowspan](https://github.com/maugenst/tabletojson/blob/complexRowspans/test/tabletojsonLocal.test.js)

**Comment by piranna** [comment]
Fixed in #45

**Comment by piranna** [comment]
Can this be closed now?

**Comment by maugenst** [comment]
Closing .... Thanks !!!!

**Comment by piranna** [comment]
> Closing .... Thanks !!!!

You are welcome! :-)

**Comment by maugenst** [comment]
Did you really test this against the test I implemented in the separate branch?

I recently checked this and it still fails:

**Comment by maugenst** [comment]
I Implemented a test ... Please check out the latest version and check your implementation against it.

**Comment by piranna** [comment]
I have just clean-up my `node_modules` and tests are passing will all the merged code in `master`...

**Comment by maugenst** [comment]
So ... I added the test on how I suppose the complex header feature to work. Please have a look on it and get back to me if you need more information or if you disagree ...

**Comment by piranna** [comment]
> Sorry ... I was wrong ... I just ran the test and it works like a charm ... :-) Sorry for the confusion!!!

Don't worry, sometimes I have this pitfalls after merges too :-)


> I'll push it to npmjs with a new minor version 1.2 ...

Thanks! :-D

**Comment by maugenst** [comment]
Jesus ... Thanks to the npm guys writing so damn good documentation ... :-(  I accidentally passed you the ownership as I tried to add you as a collaborator to this project ... Could you please be so kind to pass it back to me? I'm not able to publish any changes... Sorry for this ...

npm owner add maugenst tabletojson

**Comment by piranna** [comment]
Done. Yeah, documentation is a bit scarce...

**Comment by piranna** [comment]
Oh, and thank you for putting me as collaborator :-)
