### ISSUE TITLE
How to import tabletojson in es6

### ISSUE THREAD

**Issue by whyyes-in** [maugenst/tabletojson#56]
It's working fine for Node.js
const { Tabletojson: tabletojson } = require("tabletojson/dist");

But I want to use it in react.js, in es6 style of importing module
import {Tabletojson:tabletojson} from "tabletojson/dist"; 

Facing issues at importing...

**Comment by maugenst** [comment]
Imports are done differently than requires: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

Use `import {Tabletojson as tabletojson} from "tabletojson/dist";`
