### ISSUE TITLE
The node modules that tabletojson requires are not resolving

### ISSUE THREAD

**Issue by JorinHakai** [maugenst/tabletojson#63]
After a fresh `npm install --save tabletojson` and importing the package to a .jsx file with `import tabletojson from 'tabletojson'`, running `npm start` results in `Module not Found: Error: Can't resolve <npm dependency> in /path/to/file` for the following npm modules:
 - dns
 - fs
 - net

I tried deleting and reinstalling all node_modules, and `npm audit fix` with no luck.  I am using webpack and babel.

Any help is much appreciated! 

Errors messages here: 
`
WARNING in ./node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/cacheable-lookup/index.js
Module not found: Error: Can't resolve 'dns' in '<path>/node_modules/cacheable-lookup'

ERROR in ./node_modules/got/dist/source/request-as-event-emitter.js
Module not found: Error: Can't resolve 'fs' in '<path>/node_modules/got/dist/source'

ERROR in ./node_modules/got/dist/source/utils/get-body-size.js
Module not found: Error: Can't resolve 'fs' in '<path>/node_modules/got/dist/source/utils'

ERROR in ./node_modules/got/dist/source/utils/timed-out.js
Module not found: Error: Can't resolve 'net' in '<path>/node_modules/got/dist/source/utils'
`

**Comment by maugenst** [comment]
I updated the got dependencies. Please update to the latest version of tabletojson and retry.

**Comment by eudoxyz** [comment]
There are still errors.

`Module not found: Error: Can't resolve 'dns' in './node_modules/cacheable-lookup/source'`
`Module not found: Error: Can't resolve 'util' in './node_modules/cacheable-lookup/source'`
`Module not found: Error: Can't resolve 'os' in './node_modules/cacheable-lookup/source'`
`Module not found: Error: Can't resolve 'stream' in './node_modules/cacheable-request/node_modules/get-stream'`
`Module not found: Error: Can't resolve 'buffer' in './node_modules/cacheable-request/node_modules/get-stream'`
`Module not found: Error: Can't resolve 'url' in './node_modules/cacheable-request/src'`
`Module not found: Error: Can't resolve 'stream' in './node_modules/clone-response/src'`

Etc.

Also, this:
`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`

**Comment by maugenst** [comment]
Locally I cannot reproduce this issue since I do not have any information on the used environment/libraries. From reading the errors I got the impression that this is something with outdated versions of webpack / node /... Please set up a small testproject I can fork and have a look. Also please describe your environment where this happens.

BRM

**Comment by k-funk** [comment]
Looks like this package was not meant to be used in browsers, which should be in the `README.md`. [As stated in `got`'s README](https://www.npmjs.com/package/got):
> For browser usage, we recommend [Ky](https://github.com/sindresorhus/ky) by the same people.

If it is intended to be, then a different library should be used.

**Comment by maugenst** [comment]
I replaces got by fetch which is available from node 18 on. So as the browsers implemented fetch already the usage should be fine there as well.

**Comment by maugenst** [comment]
Please use versio 2.1.+
