### ISSUE TITLE
v2.10 converted to ESM

### ISSUE THREAD

**Issue by aarongoldenthal** [maugenst/tabletojson#82]
With v2.1.0 this package was converted from CJS to ESM, which is a breaking change and should be released as 3.0.0. It appears to be intentional with the changes in [517e47b](https://github.com/maugenst/tabletojson/commit/517e47b72168dc6b3ecfe66d74db4134060a3b18#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), but that is not captured in the documentation and the examples were not updated to reflect the change to ESM (the current CJS examples no longer work).

**Comment by maugenst** [comment]
Thanks for mentioing this. I'll update the docu and bump versions.

**Comment by maugenst** [comment]
released version 3.0.0 with updated docu and examples.
