### ISSUE TITLE
[Bug] fetch is not a funcction

### ISSUE THREAD

**Issue by yyz945947732** [maugenst/tabletojson#83]
<img width="334" alt="image" src="https://github.com/maugenst/tabletojson/assets/47586954/a9c99b1d-115b-44b9-9c9e-ce2b41634863">

I can't run this script in node environment. I think maybe you can add `node-fetch` package to the project and add polyfill like this:

```js
import fetch from 'node-fetch';

if (!globalThis.fetch) {
  globalThis.fetch = fetch;
}
```

Then this package should be able to run directly in the node environment.

**Comment by yyz945947732** [comment]
Oh, Because my node version is lower than 18.0.0. So `fetch` api is not support. 

<img width="190" alt="image" src="https://github.com/maugenst/tabletojson/assets/47586954/7ee581dd-744c-4bcf-abc5-7598d2dd0b30">

I just saw that lower versions of node cannot support this library.

**Comment by maugenst** [comment]
Thanks for your reply. 

From node 18 onwards the fetch api is available, but tagged as experimental: 
https://nodejs.org/en/blog/announcements/v18-release-announce 
or
https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch

Once you upgraded your node to 18+ it should work out of the box.
