### ISSUE TITLE
Require fetchOptions parameter when callbackFunction is not provided

### ISSUE THREAD

**Issue by 77629296** [maugenst/tabletojson#89]
The provided fetchOptions are not taking effect during the actual invocation, as it's found that the defined fetchOptions are not being used in the code.
<img width="579" alt="image" src="https://github.com/maugenst/tabletojson/assets/22374488/93e6e6c7-5752-4c38-a7d6-eab1f9404b3e">

**Comment by maugenst** [comment]
Please provide some code-part showcasing your error. The 2nd param can be either a function OR an object.

**Comment by 77629296** [comment]
`
convertUrl(url, { fetchOptions: { timeout: 300 } })
`

Thank you for your prompt reply. When I pass an object as the second parameter, fetchOptions doesn't take effect because it enters the else logic and doesn't pass fetchOptions to the fetch method.

**Comment by 77629296** [comment]
<img width="792" alt="image" src="https://github.com/maugenst/tabletojson/assets/22374488/ace87841-b093-47d8-b351-5bc3db729dc5">
Can I add fetchOptions here?

**Comment by 77629296** [comment]
I have another question, the URL has been unresponsive. For example, this piece of code:
`
tabletojson.convertUrl('https://httpbin.org/delay/60', {
  fetchOptions: {
    timeout: 300,
  }
})
`

Node's built-in fetch doesn't support timeout. I want to use node-fetch. Could you add a configuration to support custom fetch, or detect when it's running in a Node environment and use node-fetch?
`
tabletojson.convertUrl('https://httpbin.org/delay/60', {
  fetchOptions: {
    timeout: 300,
  },
  fetchHandler: ?
})
`

**Comment by maugenst** [comment]
Created a test and debugged. Tagging this as bug. Will create a fix asap.

**Comment by maugenst** [comment]
Fixed with version 4.1.2. 

For your timeout problem please use this approach: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static

**Comment by 77629296** [comment]
Sure, thank you! Your efficiency is impressive. 👍🏻
